name: JS Actions

on: [push]

jobs:
  action:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: hello-action
      uses: ./.github/actions/hello-world
      with:
        second-greeting: "A new second greeting"

